### ISSUE TITLE
Shippable secure field in shippable.yml

### ISSUE THREAD

**Issue by miguelfabre** [shippableSamples/sample-python-datastore-appengine#4]
Hi friend @anowak! I'm spanish student. I want to use shippable but I don't know what I should write in the "secure" field in the shippable.yml. (https://github.com/shippableSamples/sample-python-datastore-appengine/blob/master/shippable.yml) 
Can you help me please? Where can I find these key?

Thank you so much.

**Comment by rolandpoulter** [comment]
@miguelfabre the value for a secure environment variable comes from Shippable.com. On the subscription page you will see a lock icon with the text: "ENCRYPT ENV VARS". This will open a dialog where you can declare secure environment variables. This is useful for private keys and passwords. This way you don't have to check-in this data to you shippable YAML in plain text. When the build runs it will decrypt these variables. Let me know if this helps answer you question.

Shippable.yaml:

```
...
env:
  global:
    {paste encrypted var here}
...
```

![image](https://cloud.githubusercontent.com/assets/51327/5866509/c55e1638-a246-11e4-8621-5dd140fe3c26.png)

**Comment by miguelfabre** [comment]
Yes, it works, thank you so much!!, but know appears this error, do you know why?
![screenshot](https://cloud.githubusercontent.com/assets/8873238/5883519/82adbefc-a353-11e4-9132-43f91171e706.png)
